FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /App

COPY ApiGateway/ApiGateway.sln ./

COPY ApiGateway/src/src.csproj ./src/

RUN dotnet restore ./src/src.csproj

COPY ApiGateway/src/ ./src/

WORKDIR /App/src
RUN dotnet publish -c Release -o /App/out

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /App

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

ENV ASPNETCORE_ENVIRONMENT=Production

COPY --from=build /App/out .

ENTRYPOINT ["dotnet", "src.dll"]
